<!-- Footer Section -->
<footer>
    <!-- Container Starts -->
    <div class="container">
        <!-- Row Starts -->
        <div class="row">
            <!-- Footer Widget Starts -->
            <div class="footer-widget col-md-3 col-xs-12 wow fadeIn">
                <h3 class="small-title">
                    ABOUT Bus Ticket Reservation
                </h3>
                <p>
                    <img src="<?php echo $root ; ?>assets/img/bus22.png" alt="">
                </p>
                <p>
                   Say goodbye to long queues and welcome online bus booking! 
                </p>  

                <div class="social-links-bordered">
                    <a href="404.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Twitter">
                        <i class="fa fa-twitter">
                        </i>
                    </a>
                    <a href="404.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Facebook">
                        <i class="fa fa-facebook">
                        </i>
                    </a>
                    <a href="404.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Google+">
                        <i class="fa fa-google-plus">
                        </i>
                    </a>
                    <a href="404.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="LinkedIn">
                        <i class="fa fa-linkedin">
                        </i>
                    </a>
                </div>          
            </div><!-- Footer Widget Ends -->

            <!-- Footer Widget Starts -->
            <div class="footer-widget col-md-3 col-xs-12 wow fadeIn" data-wow-delay=".2s">
                <h3 class="small-title">
                    Our Top Routes
                </h3>
                <ul class="recent-tweets">
                    <li class="tweet">
                         <a href="#">Lahore To Islamabad</a>                
                        <br />
                        <a href="#">Lahore To multan</a> 
                        <br />
                          <a href="#">Lahore To Gujranwala</a>                
                        <br />
                        <a href="#">Lahore To Haroonabad</a> 
                        <br />
                        <a href="#">Lahore To BahawalPur</a> 
                       
                    </li>


            


                </ul>
            </div><!-- Footer Widget Ends -->

            <!-- Footer Widget Starts -->
            <div class="footer-widget col-md-3 col-xs-12 wow fadeIn" data-wow-delay=".5s">
                <h3 class="small-title">
                    Flicker Gallery
                </h3>
                <div class="plain-flicker-gallery">
                    <a href="404.html#" title="Pan Masala"><img src="<?php echo $root ; ?>assets/img/flicker/image11.jpg" alt=""></a>
                    <a href="404.html#" title="Sports Template for Joomla"><img src="<?php echo $root ; ?>assets/img/flicker/image22.jpg" alt=""></a>
                    <a href="404.html" title="Apple Keyboard"><img src="<?php echo $root ; ?>assets/img/flicker/image33.jpg" alt=""></a>
                    <a href="404.html" title="Hard Working"><img src="<?php echo $root ; ?>assets/img/flicker/image44.jpg" alt=""></a>
                    <a href="404.html" title="Smile"><img src="<?php echo $root ; ?>assets/img/flicker/image55.jpg" alt=""></a>
                    <a href="404.html" title="Puzzle"><img src="<?php echo $root ; ?>assets/img/flicker/image66.jpg" alt=""></a>
                </div>
            </div><!-- Footer Widget Ends -->

            <!-- Footer Widget Starts -->
            <div class="footer-widget col-md-3 col-xs-12 wow fadeIn" data-wow-delay=".8s">
                <h3 class="small-title">
                    Tags
                </h3>
                <div class="tagcloud">
                    <a href="#" class="tag-link-201" title="1 topic"><i class="fa fa-tags"></i> Home</a>
                    <a href="#" class="tag-link-197" title="1 topic"><i class="fa fa-tags"></i>About Us</a>
                    <a href="#" class="tag-link-195" title="1 topic"><i class="fa fa-tags"></i> Our routes</a>
                    <a href="#" class="tag-link-211" title="1 topic"><i class="fa fa-tags"></i> bus ticket</a>
                    <a href="#" class="tag-link-204" title="1 topic"><i class="fa fa-tags"></i> latest News</a>
                    <a href="#" class="tag-link-203" title="1 topic"><i class="fa fa-tags"></i> Contact Us</a>
                    
                </div>
            </div><!-- Footer Widget Ends -->
        </div><!-- Row Ends -->
    </div><!-- Container Ends -->

    <!-- Copyright -->
    <div id="copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-sm-6">
                    <p class="copyright-text">
                        ©  2015 BTRS. All right reserved. 
                    </p>
                </div>
                <div class="col-md-3  col-sm-6">
                    <p class="copyright-text pull-right">Bus <a href="#">Ticket</a> Reservation.</p>             
                </div>
            </div>
        </div>
    </div>
    <!-- Copyright  End-->

</footer>
<!-- Footer Section End-->