<?php $root = base_url(); ?>

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta content="BTRS Project" name="description"/>
    <meta content="BTRS" name="author"/>

    <title>
      BTRS - Project
    </title>
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/bootstrap.css">
    <!-- Main Style -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/main.css">
    <!-- Responsive Style -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/responsive.css">
    <!--Fonts-->
    <link rel="stylesheet" media="screen" href="<?php echo $root; ?>assets/fonts/font-awesome/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/fonts/plain/plain-fonts.css">
    
     
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/fonts/lovelo/lovelo.css">
    <!-- Extras -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/extras/owl/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/extras/owl/owl.theme.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/extras/animate.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/extras/slicknav.css">

      <!-- Color CSS Styles  --> 
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/green.css" media="screen" /> 
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/greensea.css" title="greensea" media="screen" /> 
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/default.css" title="def" media="screen" />      
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/lightblue.css" title="lightblue" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/gray.css" title="gray" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/coffee.css" title="coffee" media="screen" />    
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/orange.css" title="orange" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/wisteria.css" title="wisteria" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/colors/mblue.css" title="mblue" media="screen" />
    
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js">
    </script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js">
    </script>
    <![endif]-->
    
<!--        --------------------------------------------------------------------------------------      -->


<!--        METRONIC RELATED CSS      -->
    
    
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?php echo $root; ?>assets/metronic/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $root; ?>assets/metronic/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <!-- END GLOBAL MANDATORY STYLES -->
    
    <!-- BEGIN PAGE LEVEL STYLES -->
        <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/metronic/plugins/select2/select2_metro.css"/>
    <!-- END PAGE LEVEL SCRIPTS -->

    <!-- BEGIN THEME STYLES -->
        <link href="<?php echo $root; ?>assets/metronic/css/style-metronic.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $root; ?>assets/metronic/css/style.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $root; ?>assets/metronic/css/style-responsive.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $root; ?>assets/metronic/css/plugins.css" rel="stylesheet" type="text/css"/>
        <link href="<?php echo $root; ?>assets/metronic/css/custom.css" rel="stylesheet" type="text/css"/>
    <!-- END THEME STYLES -->

    <!-- jquery password strengthen plugin css -->
    <link rel="stylesheet" type="text/css" href="<?php echo $root; ?>assets/css/jquery.passwordstrength.css">

  </head>