<!--                THEME RELATED JS FILES               -->

<!-- JavaScript & jQuery Plugins -->
    <!-- jQuery Load -->
    <script src="<?php echo $root; ?>assets/js/jquery-min.js">
    </script>
    <!-- Bootstrap JS -->
    <script src="<?php echo $root; ?>assets/js/bootstrap.min.js">
    </script>
    <!--Text Rotator-->
    <script src="<?php echo $root; ?>assets/js/jquery.mixitup.js">
    </script>
    <!--WOW Scroll Spy-->
    <script src="<?php echo $root; ?>assets/js/wow.js">
    </script>
    <!-- OWL Carousel -->
    <script src="<?php echo $root; ?>assets/js/owl.carousel.js">
    </script>
    <!-- Placeholder 
    
    not attached, because with this jquery code all placeholder in form treated as value.
    -->
     
    <!-- Vide -->
    <script src="<?php echo $root; ?>assets/js/jquery.vide.js">
    </script>
    <!-- Skrollr -->
    
    <!-- Smooth Scroll -->
    <script src="<?php echo $root; ?>assets/js/smooth-scroll.js">
    </script>
    <!-- WayPoint -->
    <script src="<?php echo $root; ?>assets/js/waypoints.min.js">
    </script>
    <!-- CounterUp -->
    <script src="<?php echo $root; ?>assets/js/jquery.counterup.min.js">
    </script>
    <!-- ScrollTop -->
    <script src="<?php echo $root; ?>assets/js/scroll-top.js">
    </script>
    <!-- Appear -->
    <script src="<?php echo $root; ?>assets/js/jquery.appear.js">
    </script>
    <!-- Slicknav -->
    <script src="<?php echo $root; ?>assets/js/jquery.slicknav.js">
    </script>
    <!-- All JS plugin Triggers -->
    <script src="<?php echo $root; ?>assets/js/main.js">
    </script>
<!-- JavaScript & jQuery Plugins ENDS -->


<!--  ---------------------------------------------------------------------------------------      -->
    

<!--                METRONIC RELATED JS FILES               --> 
    
    
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
        <!--[if lt IE 9]>
            <script src="assets/plugins/respond.min.js"></script>
            <script src="assets/plugins/excanvas.min.js"></script> 
        <![endif]-->

        <script src="<?php echo $root; ?>assets/metronic/plugins/jquery-1.10.2.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/bootstrap-hover-dropdown/twitter-bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/jquery.cokie.min.js" type="text/javascript"></script>
        <script src="<?php echo $root; ?>assets/metronic/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->

   
    
    <!-- Jquery Password Strengthen plugin -->
    <script src="<?php echo $root; ?>assets/js/jquery.passwordstrength.js"></script>