

<!-- Roof area starts -->
<div id="roof" class="hidden-xs">
    <div class="container">

        <!-- Quick Contacts starts -->
        <div class="quick-contacts pull-left">
            <span >
                <i class="fa fa-map-marker">
                </i>
                Lahore, Pakistan
            </span>

            <!--
            <span>
                <i class="fa fa-mobile-phone">
                </i>
                0300-1234567
            </span> 
            -->

            <span>
                <i class="fa fa-envelope">
                </i>
                <a href="mailto:info@therightsol.com">info@therightsol.com</a>
            </span>
            
            
            <span>
                <i class="fa fa-building">
                </i>
                TR Solutions
            </span>
            
            
            <span>
                <i class="fa fa-edge">
                </i>
                <a href="http://www.therightsol.com">http://www.therightsol.com</a>
            </span>
        </div>
        <!-- Quick Contacts Ends -->

        <!-- Roof Social Links Starts-->
        <div class="social-links text-center pull-right">
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Twitter">
                <i class="fa fa-twitter">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Facebook">
                <i class="fa fa-facebook">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Google+">
                <i class="fa fa-google-plus">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="LinkedIn">
                <i class="fa fa-linkedin">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="YouTube">
                <i class="fa fa-youtube-play">
                </i>
            </a>
        </div>
        <!-- Roof Social Links Ends-->

    </div>
</div>
<!-- Roof area Ends -->
