

<!-- Roof area starts -->
<div id="roof" class="hidden-xs">
    <div class="container">

        <!-- Quick Contacts starts -->
        <div class="quick-contacts pull-left">
            <span >
                <i class="fa fa-map-marker">
                </i>
                Johar Town Lahore, Pakistan
            </span>

            <span>
                <i class="fa fa-mobile-phone">
                </i>
                0300-1234567
            </span>

            <span>
                <i class="fa fa-envelope">
                </i>
                <a class="__cf_email__" href="../../../cdn-cgi/l/email-protection.htm" data-cfemail="c0a5ada1a9ac80a5b8a1adb0aca5eea3afad">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">
                    /* <![CDATA[ */!function(){try{var t = "currentScript"in document?document.currentScript:function(){for (var t = document.getElementsByTagName("script"), e = t.length; e--; )if (t[e].getAttribute("data-cfhash"))return t[e]}(); if (t && t.previousSibling){var e, r, n, i, c = t.previousSibling, a = c.getAttribute("data-cfemail"); if (a){for (e = "", r = parseInt(a.substr(0, 2), 16), n = 2; a.length - n; n += 2)i = parseInt(a.substr(n, 2), 16) ^ r, e += String.fromCharCode(i); e = document.createTextNode(e), c.parentNode.replaceChild(e, c)}t.parentNode.removeChild(t); }} catch (u){}}()/* ]]> */</script>
            </span>
        </div>
        <!-- Quick Contacts Ends -->

        <!-- Roof Social Links Starts-->
        <div class="social-links text-center pull-right">
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Twitter">
                <i class="fa fa-twitter">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Facebook">
                <i class="fa fa-facebook">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="Google+">
                <i class="fa fa-google-plus">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="LinkedIn">
                <i class="fa fa-linkedin">
                </i>
            </a>
            <a href="about.html#" class="social-link" data-toggle="tooltip" data-placement="bottom" title="YouTube">
                <i class="fa fa-youtube-play">
                </i>
            </a>
        </div>
        <!-- Roof Social Links Ends-->

    </div>
</div>
<!-- Roof area Ends -->
